const statements = [
    // Group Chat & WhatsApp Chaos (1-50)
    "Never have I ever muted this group chat for more than a week.",
    "Never have I ever accidentally sent a message meant for an admin directly into this main chat.",
    "Never have I ever stalked a group member's WhatsApp profile picture or status updates in secret.",
    "Never have I ever screenshotted a massive argument here just to show people outside the group.",
    "Never have I ever lied about why I was inactive when an admin tagged me.",
    "Never have I ever stolen a custom sticker from this chat and claimed I made it.",
    "Never have I ever ignored a private message from someone in this group on purpose.",
    "Never have I ever left a group chat in a dramatic rage just to wait for an invite back.",
    "Never have I ever used a bot command over 50 times in a single day just to spam.",
    "Never have I ever pretended to agree with a hot take here just to avoid getting flamed.",
    "Never have I ever faked being sick to completely avoid a voice call or social event.",
    "Never have I ever uninstalled WhatsApp entirely just to clear my mind for a few days.",
    "Never have I ever stayed up past 5:00 AM scrolling through random group chats.",
    "Never have I ever lied about my actual age or name to people online.",
    "Never have I ever broken a phone screen out of sheer frustration or anger.",
    "Never have I ever deleted a message instantly because someone noticed a massive typo.",
    "Never have I ever created a second WhatsApp account to browse anonymously.",
    "Never have I ever dropped my phone directly on my face while typing in bed.",
    "Never have I ever read an entire 200-message argument without saying a single word.",
    "Never have I ever used an AI bot to write a text message response to a friend.",
    "Never have I ever pretended to know an anime or game someone was talking about here.",
    "Never have I ever blocked an active admin on my personal contact sheet.",
    "Never have I ever reported a group chat message by accident.",
    "Never have I ever spent money on a custom digital sticker or profile aesthetic.",
    "Never have I ever forgotten a close friend's birthday until I saw a status post.",
    "Never have I ever ghosted a group project chat because it was getting too complicated.",
    "Never have I ever sent a voice note that was longer than three minutes.",
    "Never have I ever laughed at a completely inappropriate time during a serious chat.",
    "Never have I ever re-gifted a digital download or account access to someone else.",
    "Never have I ever fallen asleep with my phone screen still active on a chat box.",
    "Never have I ever lied to my parents about what I was doing on my phone.",
    "Never have I ever stalked an absolute stranger's social profile for over an hour.",
    "Never have I ever kept a secret that actively caused massive drama for other people.",
    "Never have I ever used someone else's login premium credentials without asking them.",
    "Never have I ever deleted my entire Google search history out of sheer sudden panic.",
    "Never have I ever pretended to laugh at a meme that wasn't funny at all.",
    "Never have I ever spent an entire 24 hours inside my room without stepping outside.",
    "Never have I ever ignored a phone call from my best friend because I was gaming.",
    "Never have I ever watched an entire anime series in a single day.",
    "Never have I ever spent my last bit of money on something completely useless online.",
    "Never have I ever fallen down a flight of stairs while looking directly at my phone.",
    "Never have I ever used a custom gothic font that completely broke the bot's text readers.",
    "Never have I ever tried to guess someone's phone password and locked their device.",
    "Never have I ever had a crush on a completely fictional anime or gaming character.",
    "Never have I ever sent a message to the completely wrong group and panicked.",
    "Never have I ever changed my profile bio text to something deeply dark and edgy.",
    "Never have I ever stayed in pajamas for three consecutive days while online.",
    "Never have I ever tried to program or deploy a bot framework and failed on the first try.",
    "Never have I ever been completely kicked out of a public digital community venue.",
    "Never have I ever run out of cellular data right in the middle of an intense text match.",

    // Darker Confessions & Habits (51-100)
    "Never have I ever double-texted someone who clearly ignored my first message.",
    "Never have I ever set a fake status update just to see if a specific person would view it.",
    "Never have I ever pretended to be out of the house just to avoid a phone call.",
    "Never have I ever created a completely fake internet persona to argue with strangers.",
    "Never have I ever checked my phone notifications within two minutes of waking up.",
    "Never have I ever stayed awake for over 24 hours straight playing video games.",
    "Never have I ever laughed out loud at a text while someone was talking to me in real life.",
    "Never have I ever hid my phone screen when a family member walked past me.",
    "Never have I ever liked my own social media post from an alternative secondary account.",
    "Never have I ever forgotten the name of someone I was actively talking to online.",
    "Never have I ever pretended my phone died because I didn't want to reply anymore.",
    "Never have I ever downloaded a modified WhatsApp version just to see deleted messages.",
    "Never have I ever spent more than five hours straight watching short-form video edits.",
    "Never have I ever re-watched my own posted video over ten times just to look at it.",
    "Never have I ever felt genuinely jealous of someone else's digital community setup.",
    "Never have I ever used a translation app to pretend I spoke another language fluently.",
    "Never have I ever ghosted a conversation because the person used terrible text formatting.",
    "Never have I ever accidentally liked a years-old picture while stalking someone's feed.",
    "Never have I ever sent a voice note, listened to it instantly, and deleted it out of cringe.",
    "Never have I ever lied about seeing a movie or show just to join a discussion.",
    "Never have I ever faked having an elite setup just to impress people in a tech chat.",
    "Never have I ever left someone on 'read' for over a day on purpose.",
    "Never have I ever used a custom sound bite or audio modifier in a public chat layout.",
    "Never have I ever spent an hour editing a single profile picture to look cooler.",
    "Never have I ever stayed up late reading deep lore about a fictional universe.",
    "Never have I ever been blocked by a bot because I spammed the commands too fast.",
    "Never have I ever pretended to be busy just to get out of doing household chores.",
    "Never have I ever eaten a piece of food that fell on the floor past the five-second rule.",
    "Never have I ever searched up my own username on a search engine to see what appears.",
    "Never have I ever lied about having a massive emergency to get out of a commitment.",
    "Never have I ever argued with someone online for over an hour over something completely pointless.",
    "Never have I ever read a private message from the notification bar so it wouldn't show read receipts.",
    "Never have I ever had a nickname so embarrassing that I keep it hidden from this chat.",
    "Never have I ever unblocked someone just to check if they changed their profile picture.",
    "Never have I ever pretended to know how to fix a technical error when I had absolutely no clue.",
    "Never have I ever deleted a status update because it didn't get enough views fast enough.",
    "Never have I ever worn the exact same clothes for three days straight while staying inside.",
    "Never have I ever typed out a massive angry paragraph response and deleted it instead of sending.",
    "Never have I ever spent money on in-game cosmetics instead of buying real-life essentials.",
    "Never have I ever pretended to sleep when someone came into my room to check on me.",
    "Never have I ever accidentally sent a screenshot of a chat back to the exact same person.",
    "Never have I ever stayed in bed for an entire day doing absolutely nothing but scrolling.",
    "Never have I ever lied about my skills to pass an online community registration or test.",
    "Never have I ever used a complete stranger's open public Wi-Fi network without security.",
    "Never have I ever hidden a piece of physical trash somewhere inside my room instead of throwing it away.",
    "Never have I ever broken a promise to a friend over something incredibly petty.",
    "Never have I ever re-watched an entire anime arc purely for the background music track.",
    "Never have I ever faked a laugh in a voice note just to match the energy of the chat.",
    "Never have I ever pretended my microphone or camera was broken to avoid joining a live call.",
    "Never have I ever locked myself out of my own account because I forgot the new password.",

    // Chaotic Group Interrogations (101-150)
    "Never have I ever thought about kicking an active member from a group just because they were annoying.",
    "Never have I ever muted an admin because they were spamming the ping notifications too much.",
    "Never have I ever been a member of a group chat that got completely hijacked or wiped.",
    "Never have I ever used a completely blank profile picture to appear mysterious or edgy.",
    "Never have I ever laughed at a completely terrible joke just because an admin made it.",
    "Never have I ever copied someone else's exact status quote or bio text word for word.",
    "Never have I ever joined a group chat filled with total strangers just to spectate.",
    "Never have I ever left a chat group because the color scheme or logo looked terrible.",
    "Never have I ever private messaged an admin to complain about a feature that wasn't working.",
    "Never have I ever spent an entire night customizing the layout interface of an application.",
    "Never have I ever used a sticker pack that was so chaotic it almost got me banned.",
    "Never have I ever pretended to ignore a direct tag by claiming my notifications were broken.",
    "Never have I ever seen a massive server argument break out and immediately grabbed snacks to watch.",
    "Never have I ever private messaged someone from a group without talking to them in public first.",
    "Never have I ever lied about my physical location to someone who asked me in a chat.",
    "Never have I ever used a custom automated script to send a message at an exact specific time.",
    "Never have I ever joined a group voice room and stayed completely silent the entire time.",
    "Never have I ever been roasted so hard in a group chat that I didn't type for a full day.",
    "Never have I ever used an image search tool to track down a profile picture someone was using.",
    "Never have I ever deleted a group chat history entirely out of anger or frustration.",
    "Never have I ever faked a status update to show off a lifestyle choice I didn't actually make.",
    "Never have I ever created a separate hidden group chat just to plan a project behind the scenes.",
    "Never have I ever been completely overwhelmed by a conversation and closed the app instantly.",
    "Never have I ever downloaded a file from a group chat that contained a hidden script mistake.",
    "Never have I ever spent an hour trying to think of a cool username for a community profile.",
    "Never have I ever pretended to be an expert on a topic just to win an online debate.",
    "Never have I ever had my chat messages shared as a meme template by other group members.",
    "Never have I ever felt personally targeted by a generic message an admin posted.",
    "Never have I ever hidden my online active status from everyone on my contact sheet.",
    "Never have I ever stayed up past dawn watching random video editing tutorials online.",
    "Never have I ever been completely confused by a conversation layout and pretended to understand.",
    "Never have I ever used an alternative font style that made my texts completely unreadable.",
    "Never have I ever joined a chat group and left it within less than sixty seconds flat.",
    "Never have I ever had a custom sticker made out of an embarrassing message I sent.",
    "Never have I ever ignored a notification for a full day just because I didn't want to think of a reply.",
    "Never have I ever downloaded an entirely separate application just to use one custom sticker pack.",
    "Never have I ever been part of a group chat that had its name changed over ten times in one day.",
    "Never have I ever pretended to be asleep when my phone buzzed with an urgent community tag.",
    "Never have I ever forgotten to save a database session code and had to rebuild everything from scratch.",
    "Never have I ever used a highly dramatic background wallpaper for a single specific chat window.",
    "Never have I ever sent a message that made a whole group chat go completely silent for over an hour.",
    "Never have I ever copied a configuration script file directly without checking what it actually did.",
    "Never have I ever been a moderator in a community that collapsed due to internal arguments.",
    "Never have I ever changed my profile layout theme to match the aesthetic of a fictional universe.",
    "Never have I ever hidden my phone under a pillow or blanket so no one could see the screen light.",
    "Never have I ever used a completely custom text signature layout at the end of every message.",
    "Never have I ever had an online interaction that made me completely question my life choices.",
    "Never have I ever spent an entire afternoon organizing files inside a project directory.",
    "Never have I ever used a bot command to kick myself from a test group chat on purpose.",
    "Never have I ever been active in a group chat while sitting directly in a school class or meeting.",

    // Real Life Absurdity & Lifestyle (151-200)
    "Never have I ever tried to talk to an animal as if it fully understood human language.",
    "Never have I ever stared at an empty refrigerator for two straight minutes hoping food would appear.",
    "Never have I ever spent over half an hour looking for an object that was actively in my hand.",
    "Never have I ever walked into a room and completely forgotten what I went in there to do.",
    "Never have I ever sung a song completely out loud while wearing headphones in public.",
    "Never have I ever pretended to check my phone to look busy when walking past a group of people.",
    "Never have I ever tripped on a completely flat surface and looked around to see if anyone saw.",
    "Never have I ever binge-watched a show I absolutely hated just to see how terrible the ending was.",
    "Never have I ever tried to balance a physical object on my head while walking around my room.",
    "Never have I ever spent money on a premium subscription and forgot to use it for a full month.",
    "Never have I ever stayed inside my house for an entire weekend without seeing direct sunlight.",
    "Never have I ever tried to use mind control on a physical object to make it move towards me.",
    "Never have I ever laughed at a memory out loud in a quiet room by myself.",
    "Never have I ever had a dream that was so realistic I woke up angry at a real-life friend.",
    "Never have I ever read the ending spoiler of a book or movie before I even started watching it.",
    "Never have I ever spent an hour organizing my desktop or phone home screen layout.",
    "Never have I ever tried to calculate exactly how much sleep I would get if I fell asleep right that second.",
    "Never have I ever bought an electronic device solely based on how cool the dark aesthetic looked.",
    "Never have I ever accidentally spoken out loud while thinking about a text conversation.",
    "Never have I ever hidden a physical snack in my room so my family members wouldn't eat it.",
    "Never have I ever listened to the exact same song on repeat for over three hours straight.",
    "Never have I ever worn mismatched socks outside the house because I was in a rush.",
    "Never have I ever pretended to understand a highly complex topic when I had zero clue what it meant.",
    "Never have I ever looked at my own reflection in a dark screen and judged my posture.",
    "Never have I ever spent money on an application and regretted it within less than five minutes.",
    "Never have I ever had a conversation with myself in the mirror to practice an argument.",
    "Never have I ever stayed up late looking at historical mysteries or unexplainable anomalies.",
    "Never have I ever forgotten where I parked a bicycle or walked to after leaving a store.",
    "Never have I ever pretended to like a specific food choice just to be polite to a host.",
    "Never have I ever spent over an hour trying to clear space on my phone's internal storage.",
    "Never have I ever had a song stuck in my head for three days straight without knowing the lyrics.",
    "Never have I ever opened an app, closed it instantly, and opened the exact same app a second later.",
    "Never have I ever tried to clean a device screen and made it look significantly dirtier instead.",
    "Never have I ever stayed awake past dawn simply because I lost track of time completely.",
    "Never have I ever lied about having seen a classic legendary film just to fit into a group.",
    "Never have I ever spent an entire day wearing a heavy blanket like a dark cloak.",
    "Never have I ever tried a strange food combination that sounded disgusting but tasted incredible.",
    "Never have I ever gotten completely lost in a physical location I have visited multiple times.",
    "Never have I ever watched a video edit frame-by-frame just to see how the creator matched the cuts.",
    "Never have I ever deleted an entire photo album because looking at old memories was too cringe.",
    "Never have I ever tried to type a full paragraph with my eyes completely closed as a challenge.",
    "Never have I ever set over five consecutive alarms spaced two minutes apart to wake up.",
    "Never have I ever spent a full hour looking at custom keyboard themes or font style packs.",
    "Never have I ever accidentally dropped a physical object into a hard-to-reach gap behind furniture.",
    "Never have I ever stayed up late planning out a massive project that I abandoned the next morning.",
    "Never have I ever pretended to know a song's lyrics by just humming along with the melody line.",
    "Never have I ever spent an absolute fortune on snacks right before starting a long text gaming match.",
    "Never have I ever looked up at the night sky and felt completely swallowed by the endless void.",
    "Never have I ever had my phone battery die at the exact moment I was about to type something critical.",
    "Never have I ever been completely satisfied with my digital setup layout code configuration."
];

module.exports = {
    name: 'nhie',
    category: 'games',
    description: 'Play Never Have I Ever in The Void',
    async execute(client, m) {
        const statement = statements[Math.floor(Math.random() * statements.length)];

        const nhieMessage = `
 ╭───「 《♤ THE VOID ♤》 NHIE 」
 │ 
 │ 👤 **Challenger:** @${m.sender.split('@')[0]}
 │ 
 │ 👉 **Statement:** ${statement}
 │ 
 ╰───────────────────────────
 *Drop a 💀 reaction if you are GUILTY of this!*`;

        await client.sendMessage(m.chat, { text: nhieMessage, mentions: [m.sender] }, { quoted: m });
    }
};
  
