const truths = [
    // --- WAVE 1: TRUTHS (1-100) ---
    "What is the most awkward text message you have ever received?",
    "Have you ever spent an entire day in bed doing absolutely nothing but scrolling this chat?",
    "What is the most controversial opinion you hold that you keep secret from this group?",
    "Have you ever fallen in public and pretended like nobody saw you?",
    "What is the most ridiculous thing you believed as a small child?",
    "Have you ever lied to a doctor or nurse about your daily habits?",
    "What is the worst gift you have ever received from a family member?",
    "Have you ever broken a bone doing something completely stupid?",
    "What is the most embarrassing thing you have ever searched on Google?",
    "Have you ever pretended to be busy just to avoid replying to someone here?",
    "What is the most cringe username you used when you were younger?",
    "Have you ever laughed at a completely inappropriate time in real life?",
    "What is the longest you have gone without brushing your teeth?",
    "Have you ever re-gifted something that someone else gave you?",
    "What is the most embarrassing thing you have ever done while drunk or extremely tired?",
    "Have you ever fallen in love with a fictional character?",
    "What is the worst nightmare you can remember having recently?",
    "Have you ever stalked a complete stranger on social media for hours?",
    "What is the childish habit you haven't been able to break?",
    "Have you ever lied about having an emergency to get out of a group event?",
    "What is the most petty argument you have ever had with a sibling or friend?",
    "Have you ever dropped your phone directly onto your face while reading in bed?",
    "What is the most ridiculous excuse you have used for being late?",
    "Have you ever worn the exact same clothes for three days straight while staying inside?",
    "What is the most awkward encounter you've had with an authority figure?",
    "Have you ever deleted your search history out of pure sudden panic?",
    "What is a secret hobby you have that nobody else knows about?",
    "Have you ever spent money you didn't have just to impress someone online?",
    "What is the most embarrassing thing you've said out loud by accident?",
    "Have you ever stalked a group member's status updates without them knowing?",
    "What is the longest you have gone without checking your phone notifications?",
    "Have you ever lied about your location to get out of hanging out?",
    "What is the most awkward silence you have ever had to sit through?",
    "Have you ever pretended to be someone else online to get information?",
    "What is the worst impulse purchase you have ever made online?",
    "Have you ever ruined a surprise party or gift for someone by accident?",
    "What is the most cringe thing you have ever texted an absolute stranger?",
    "Have you ever been caught talking to yourself when you thought you were alone?",
    "What is the most ridiculous reason you have ever blocked someone?",
    "Have you ever borrowed something and never returned it on purpose?",
    "What is the most embarrassing nickname your family calls you?",
    "Have you ever ghosted someone because their texting style was annoying?",
    "What is the most desperate thing you have ever done for attention?",
    "Have you ever accidentally liked a years-old photo while stalking someone?",
    "What is the worst text format mistake you have ever made?",
    "Have you ever kept a secret that actively caused drama for other people?",
    "What is the most awkward thing that happened to you on a bus or train?",
    "Have you ever lied about watching a popular anime just to fit in?",
    "What is the most ridiculous thing you have ever done on a dare?",
    "Have you ever hidden a piece of trash instead of throwing it away properly?",
    "What is something you are deeply insecure about that you never talk about?",
    "Have you ever blamed a mistake you made on someone else to save yourself?",
    "What is the pettiest reason you've ever ended a friendship with someone?",
    "Have you ever read someone else's private text messages without them knowing?",
    "What is the biggest lie you have ever told your parents without getting caught?",
    "Have you ever pretended to like a food you hated just to be polite?",
    "What is the most expensive thing you have ever stolen or broken?",
    "Have you ever ignored a call from your best friend on purpose because you were gaming?",
    "What is the longest time you have ever spent completely isolated in your room?",
    "Have you ever created a fake social media account just to spy on an ex or enemy?",
    "What is the most embarrassing song on your current favorite playlist?",
    "Have you ever cried during an anime episode or a movie? Which one?",
    "What is the worst habit you have that you hide from people in real life?",
    "Have you ever lied about your age online to access a community or game?",
    "What is the most useless talent you possess?",
    "Have you ever accidentally sent a screenshot of a conversation back to the person you screenshotted?",
    "What is the most ridiculous rumors you've ever heard about yourself?",
    "Have you ever been kicked out of a public establishment or online server?",
    "What is the biggest misconception people have about your personality?",
    "Have you ever used someone else's login credentials without their direct permission?",
    "What is the most childish thing you still own and refuse to throw away?",
    "Have you ever hidden your phone screen when someone walked past you?",
    "What is the worst physical pain you have ever experienced?",
    "Have you ever ghosted a group project because it was getting too stressful?",
    "What is the most illegal thing you have ever done and completely gotten away with?",
    "Have you ever pretended to sleep just to avoid talking to someone in your house?",
    "What is the most cringe status update you have ever posted on WhatsApp?",
    "Have you ever been caught in a massive lie that completely ruined your reputation?",
    "What is a thought you've had that makes you think you might be a bit of a villain?",
    "Have you ever spent real money on a digital item and instantly regretted it?",
    "What is the most annoying trait a person can have in a group chat?",
    "Have you ever unblocked someone just to see if their profile picture changed?",
    "What is the longest you have gone without showering or bathing?",
    "Have you ever felt genuinely jealous of a group member's setup or lifestyle?",
    "What is the most embarrassing thing that has ever happened to you at school or work?",
    "Have you ever broken a promise that you knew you wouldn't keep from the start?",
    "What is the most bizarre food combination you secretly eat and enjoy?",
    "Have you ever tried to fix a technical error, broke it worse, and blamed the software?",
    "What is the most dramatic breakdown you've ever had over something incredibly small?",
    "Have you ever been completely terrified of a supernatural story or horror game?",
    "What is the meanest thing you have ever said to someone's face?",
    "Have you ever looked at your reflection in a dark screen and judged yourself?",
    "What is a secret that you will literally take to your grave?",
    "Have you ever been caught slacking off by a boss, teacher, or admin?",
    "What is the most uncomfortable situation you have ever had to sit through?",
    "Have you ever lied to get a discount or a free item online?",
    "What is the most ridiculous thing you've ever done to get a crush's attention?",
    "Have you ever deleted an entire photo archive because the memories were too cringe?",
    "What is the most chaotic thing you have ever witnessed break out in a group chat?",
    "Have you ever been completely satisfied with your custom bot configuration?",

    // --- WAVE 2: TRUTHS (101-200) ---
    "Have you ever double-texted someone who clearly left you on read for over a day?",
    "What is the longest time you have ever spent lurking in a voice chat without speaking?",
    "Have you ever created a fake argument online just to pass the time?",
    "What is the most recent thing that made you genuinely angry in this community?",
    "Have you ever uninstalled an application completely out of sheer social frustration?",
    "What is the most petty reason you have ever blocked an active phone contact?",
    "Have you ever lied about your real-life skills to sound more professional online?",
    "What is the absolute longest duration you have kept your phone screen continuously active?",
    "Have you ever screenshot a private conversation to use it as leverage later?",
    "What is the most cringe text message inside your archived or hidden chats right now?",
    "Have you ever pretended to love an anime series just because a group admin liked it?",
    "What is the absolute worst meal you have ever cooked or prepared for yourself?",
    "Have you ever used an alternative secondary profile to check on a closed chat room?",
    "What is the most hours you have spent watching edits or short-form clips in one day?",
    "Have you ever muted an entire group chat permanently because the pings were annoying?",
    "What is the most awkward thing you have accidentally posted on a status update?",
    "Have you ever lied to your closest friends about why you couldn't hang out?",
    "What is the most embarrassing physical injury you got while doing literally nothing?",
    "Have you ever pretended your internet connection failed to escape an awkward debate?",
    "What is the most useless purchase you have made solely because it had a dark aesthetic?",
    "Have you ever used a translation engine to talk to someone and pretended it was natural?",
    "What is a piece of advice someone gave you that completely ruined your plans?",
    "Have you ever stayed up past dawn troubleshooting a single line of script or code?",
    "What is the absolute worst movie you have ever watched from start to finish?",
    "Have you ever been caught looking at your phone during a completely silent event?",
    "What is the strangest phobia or fear that you still possess to this day?",
    "Have you ever hidden a broken object in your house so your parents wouldn't find it?",
    "What is the longest time you have gone without leaving your house boundaries?",
    "Have you ever deleted a message instantly because no one responded within two minutes?",
    "What is the most dramatic text you have ever sent that you instantly regretted?",
    "Have you ever been kicked or banned from a community chat without knowing why?",
    "What is the most childish argument you have participated in during the past month?",
    "Have you ever pretended to know a song lyrics by just making up random sounds?",
    "What is the most embarrassing thing currently sitting inside your bedroom trash can?",
    "Have you ever used a profile picture that belonged to an entirely different person?",
    "What is the most petty thing you have done to get back at a family member?",
    "Have you ever skipped a meal entirely just because you didn't want to leave your setup?",
    "What is the most text messages you have ever received from a single person in one night?",
    "Have you ever been caught singing a song completely out of tune by a stranger?",
    "What is the biggest waste of money you have ever committed inside a video game?",
    "Have you ever pretended to be asleep while a family member was calling your name?",
    "What is the most awkward nickname your friends have ever given you in real life?",
    "Have you ever read a message from the notification layout just to avoid sending a read receipt?",
    "What is the most hours you have spent continuously playing a single video game?",
    "Have you ever unblocked someone for less than five minutes just to stalk their bio?",
    "What is the most embarrassing typo you have ever made in a professional message?",
    "Have you ever dropped a piece of food on the floor, picked it up, and ate it anyway?",
    "What is the absolute edgiest status or bio text you have ever written?",
    "Have you ever been completely active in a chat room while sitting directly in a classroom?",
    "What is the most chaotic argument you have ever witnessed unfold in a digital group?"
];

const dares = [
    // --- WAVE 1: DARES (1-100) ---
    "Send the 5th picture in your phone gallery to this group chat immediately.",
    "Change your WhatsApp status to 'I am completely lost in the void' for 24 hours.",
    "Send a 15-second voice note singing the absolute worst song you know.",
    "Tag a random member here and text them 'I know your deepest secret.'",
    "Screenshot your phone's battery usage and screen time and send it here.",
    "Change your WhatsApp profile picture to a completely cursed meme for 12 hours.",
    "Text a random contact outside this group 'Goodbye forever' and post their reply.",
    "Send a voice note whispering something completely gibberish into the chat.",
    "Screenshot your WhatsApp archive list and send it to the group right now.",
    "Tag the most inactive member here and text them 'Wake up, the void calls.'",
    "Send the funniest or most cringe sticker you have in your collection.",
    "Change your WhatsApp display name to 'ERROR: SYSTEM FAILURE' for the rest of the day.",
    "Screenshot your recent call logs and send it to the group without context.",
    "Send a voice note repeating whatever the person before you typed out loud.",
    "Tag an admin and tell them they are doing a terrible job, then don't explain why.",
    "Type a full paragraph praising the bot creator and send it here.",
    "Send a screenshot of your Google search history from the past 24 hours.",
    "Text your best friend 'I don't think we can be friends anymore' and show the reply.",
    "Send a voice note laughing hysterically like an anime villain for 10 seconds.",
    "Change your profile picture to a solid pitch-black square for the week.",
    "Tag three members here and tell them which anime character they remind you of.",
    "Type your next 5 messages using only emojis and absolutely no letters.",
    "Send a voice note clearing your throat loudly for 15 seconds straight.",
    "Screenshot your home screen layout and show the group how messy it is.",
    "Text a family member 'I accidentally joined a cult' and show the group their reply.",
    "Send a message where every single word is capitalized backwards.",
    "Tag someone you haven't spoken to in a while here and say 'We need to talk.'",
    "Send a voice note speaking in a completely fake accent for 30 seconds.",
    "Change your WhatsApp status to the last text message you received in this group.",
    "Screenshot your custom sticker folder and show how many you've saved.",
    "Type a message backwards to the next person who asks a question here.",
    "Send a voice note explaining how to cook water as if it's a gourmet meal.",
    "Tag the person directly above you in chat and call them your master for 10 minutes.",
    "Send a screenshot of your phone's internal storage space.",
    "Text a random number 'The package has been delivered' and show the group.",
    "Send a voice note trying to beatbox for 15 seconds straight.",
    "Change your chat wallpaper to something ridiculous, screenshot it, and send it.",
    "Type a message explaining why the dark void aesthetic is superior.",
    "Tag two random members and tell them they are officially married now.",
    "Send a voice note mimicking a cat or dog fight perfectly.",
    "Screenshot your block list on WhatsApp and drop it into the chat box.",
    "Text an admin 'Please forgive me' and don't reply to their follow-up questions.",
    "Send a voice note where you talk as fast as humanly possible for 20 seconds.",
    "Change your profile picture to the default blank WhatsApp silhouette.",
    "Type a long poetic message dedicated to the bot running this group chat.",
    "Tag a random person and tell them they smell like old cheese.",
    "Send a screenshot of your favorite music playlist's top 5 songs.",
    "Send a voice note crying dramatically for absolutely no reason.",
    "Text your closest friend 'I am moving to Antarctica tomorrow' and show the reply.",
    "Type your next message using only dark gothic or distorted symbols.",
    "Go look at the closest wall and stare at it for 2 entire minutes without blinking.",
    "Eat a single slice of raw onion or a spoonful of a hot condiment right now.",
    "Do 20 jumping jacks right now and send a voice note showing you are out of breath.",
    "Text your parents 'I lost my phone' and show the group how long it takes them to notice.",
    "Drink an entire large glass of ice-cold water in less than 15 seconds straight.",
    "Whisper a secret out loud to your dark, empty room and send the audio here.",
    "Drop your phone on the floor from waist height and screenshot the screen to prove it works.",
    "Go find a mirror and stare at yourself with a blank expression for a full minute.",
    "Put an ice cube down your shirt or down your back and hold it there until it melts completely.",
    "Open your window right now and yell 'The void is watching!' as loud as you can.",
    "Write 'I am a fool' on a piece of paper, tape it to your forehead, and keep it there.",
    "Eat a spoonful of plain sugar, salt, or flour and send a voice note of your reaction.",
    "Mix two completely random liquids from your kitchen together and take a tiny sip.",
    "Do a 1-minute plank right now and send a voice note explaining how painful it was.",
    "Text a random contact 'Do you believe in ghosts?' out of absolute nowhere.",
    "Try to balance a book or an object on your head for 2 minutes without it falling.",
    "Talk in a deep, hushed whisper for the next three voice notes you send here.",
    "Do your absolute best impression of an anime character and send the voice note.",
    "Text your most recent contact outside this chat a single word: 'Run.'",
    "Write a short 3-line poem about a potato and read it out loud in a voice note.",
    "Close your eyes completely and try to type your full name without making a single typo.",
    "Put your socks on your hands for the next 30 minutes while using your phone.",
    "Send a voice note where you try to whistle a famous movie theme tune perfectly.",
    "Text a sibling or friend 'Can I borrow your brain tomorrow?' and show the reply.",
    "Spin around in circles 10 times quickly and then try to type a perfectly straight sentence.",
    "Put on your clothes completely inside out and wear them like that for an hour.",
    "Send a voice note explaining your favorite anime plot in less than 10 seconds.",
    "Try to touch your nose with your tongue and send a picture of the attempt.",
    "Text a contact you haven't talked to in a year a simple 'Hey, remember me?'",
    "Draw a terrible face on your thumb with a pen and show it to the group chat.",
    "Stand on one foot for 2 minutes straight without touching anything around you.",
    "Send a voice note reading a random sentence from the closest book near you.",
    "Text someone 'I know what you did last summer' and screenshot their reaction.",
    "Pour a few drops of cold water on your head right now before typing your next message.",
    "Give a 30-second speech about why carrots are superior to all other vegetables.",
    "Try to hold your breath for 45 seconds straight and type 'Done' when finished.",
    "Text your best friend a completely random string of gibberish and act like it makes sense.",
    "Go brush your teeth right now and send an audio note of the scrubbing sound.",
    "Send a voice note howling at the moon like a lone wolf for 10 seconds straight.",
    "
