const truths = [
    // 1-50: Group Chat Secrets
    "What was your absolute first impression of this group chat?", "Who is the most intimidating person in this group to you?", 
    "Have you ever muted this group chat because it was getting annoying?", "Which member here do you think talks the absolute most nonsense?",
    "If you had to delete one admin from power right now, who would it be?", "Have you ever screenshotted a message from this chat to mock it elsewhere?",
    "Who do you think is the most underrated person in this group?", "If this group chat was a movie, who would be the main villain?",
    "Who is the most chaotic person in this chat layout?", "Have you ever ignored a direct tag in this group on purpose?",
    "Who here do you think has the absolute worst taste in music?", "If you could meet only one person from this chat in real life, who?",
    "Who is the most forgettable member currently active in this group?", "Have you ever started an argument here just because you were bored?",
    "Which member's profile picture do you find the most cringe?", "If you had to clear your chat history with one person here forever, who?",
    "Who do you think spends way too much time active on WhatsApp?", "Have you ever private messaged someone here to complain about someone else?",
    "Who here do you think tries way too hard to seem cool or edgy?", "If you were forced to give up group admin power to anyone else, who?",
    "Who is the first person you would kick if someone hijacked the group?", "Have you ever read a long argument here and just laughed at them?",
    "Who do you think is secretly the softest person in this chat?", "Which member here would you trust to keep a highly illegal secret?",
    "Have you ever lied in this group chat to make yourself look better?", "Who do you think has the most attractive voice notes here?",
    "If you could trade lives with one member in this chat for a day, who?", "Who is the most dramatic person when things go wrong here?",
    "Have you ever left this group out of anger and waited for an invite back?", "Who do you think has the lowest screen time in this entire chat?",
    "Which member here gives off the strongest 'main character' energy?", "Who here do you think is most likely to become a billionaire?",
    "Who is the most mysterious member who rarely talks but always watches?", "Have you ever regretted adding someone from this group to your contacts?",
    "Who here do you think is the worst at text-based games?", "If the world was ending, which member would you call first?",
    "Who do you think is the funniest person in this entire chat layout?", "Have you ever copied someone else's sticker pack from this group?",
    "Who here do you think has the absolute messiest real-life room?", "If you had to block one person here on all social media, who is it?",
    "Who do you think is secretly a multi-millionaire hiding in this group?", "Have you ever ghosted a private message from an admin here?",
    "Who do you think has the absolute strangest sleeping schedule?", "If you could force one inactive member to type right now, who?",
    "Who here do you think has the most chaotic stickers in their panel?", "Have you ever felt personally attacked by a bot command response?",
    "Who do you think is the smartest person in this chat academically?", "If this group was trapped on a deserted island, who gets eaten first?",
    "Who here has the most aesthetic status updates on WhatsApp?", "Who do you think is secretly reading every single message right now?",

    // 51-150: Deep, Dark & Sarcastic Truths
    "What is a dark secret you have never shared with any living soul?", "What is the biggest lie you have ever told your parents with a straight face?",
    "Have you ever pretended to be sick just to avoid a social gathering?", "What is the most illegal thing you have ever gotten away with?",
    "What is the longest you have gone without taking a proper shower?", "Have you ever stalked an ex's social media profile from a fake account?",
    "What is the most embarrassing thing your parents have caught you doing?", "If you could erase one day from your past completely, which day?",
    "Have you ever stolen something small from a store or a friend's house?", "What is the most cringe-worthy phase you went through in school?",
    "Have you ever cried yourself to sleep over something completely stupid?", "What is the meanest thing you have ever said behind a friend's back?",
    "What is your biggest fear that you think people would laugh at?", "Have you ever broken something expensive and blamed it on someone else?",
    "What is the most useless thing you have ever spent your money on?", "Have you ever text-flirted with two people at the exact same time?",
    "What is the worst advice you have ever given someone on purpose?", "Have you ever cheated on a test or exam that changed your final grade?",
    "What is the most childish thing you still do on a daily basis?", "Have you ever blamed a weird smell in the room on a pet or sibling?",
    "What is a movie or show you secretly love but would never admit to?", "Have you ever deleted a social media post because it got zero likes?",
    "What is the most embarrassing contact name saved in your phone book?", "Have you ever pretended to not see someone in public to avoid talking?",
    "What is the worst physical pain you have ever experienced in your life?", "Have you ever broken a promise that actually ruined someone's day?",
    "What is the strangest food combination you secretly enjoy eating?", "Have you ever pretended to understand a joke when you actually didn't?",
    "What is the biggest mistake you made that turned out to be a blessing?", "Have you ever looked at yourself in the mirror and started crying?",
    "What is the most ridiculous rumor you have ever started about someone?", "Have you ever ignored a call from your best friend on purpose?",
    "What is the most expensive thing you have ever broken by accident?", "Have you ever lied about your age to get into a website or event?",
    "What is the worst haircut or hairstyle you have ever had to endure?", "Have you ever used someone else's Netflix or Spotify without asking?",
    "What is the most toxic trait you secretly know you possess?", "Have you ever fallen asleep in a public place and woken up embarrassed?",
    "What is the longest time you have spent scrolling on your phone?", "Have you ever sent a text message to the completely wrong person?",
    "What is a compliment someone gave you that you think was a total lie?", "Have you ever faked a laugh just to make someone feel better?",
    "What is the most embarrassing song on your current playlist?", "Have you ever lied on your resume or a job/school application?",
    "What is the pettiest thing you have ever done to get back at someone?", "Have you ever forgotten a close friend's birthday completely?",
    "What is the strangest dream you have ever had about a real person?", "Have you ever eaten food that fell on the floor past the 5-second rule?",
    "What is the most useless talent or skill that you possess?", "Have you ever snooped through someone's room or drawers without permission?",
    "What is the most awkward text message you have ever received?", "Have you ever spent an entire day in bed doing absolutely nothing?",
    "What is the most controversial opinion you hold that you keep secret?", "Have you ever fallen in public and pretended it didn't happen?",
    "What is the most ridiculous thing you believed as a small child?", "Have you ever lied to a doctor or nurse about your lifestyle?",
    "What is the worst gift you have ever received from a family member?", "Have you ever broken a bone doing something incredibly stupid?",
    "What is the most embarrassing thing you have ever searched on Google?", "Have you ever pretended to be busy just to get off a phone call?",
    "What is the most cringe username you used when you were younger?", "Have you ever laughed at a completely inappropriate moment in public?",
    "What is the longest you have gone without brushing your teeth?", "Have you ever re-gifted something that someone else gave to you?",
    "What is the most embarrassing thing you have ever done while drunk or tired?", "Have you ever fallen in love with a fictional anime character?",
    "What is the worst nightmare you can remember having recently?", "Have you ever stalked a complete stranger on the internet for hours?",
    "What is the most childish habit you haven't been able to break?", "Have you ever lied about having an emergency to leave work or school?",
    "What is the most petty argument you have ever had with a sibling?", "Have you ever dropped your phone directly onto your face while typing?",
    "What is the most ridiculous excuse you have used for being late?", "Have you ever worn the exact same clothes for three days straight?",
    "What is the most awkward encounter you've had with an authority figure?", "Have you ever deleted your search history out of sheer panic?",
    "What is a secret hobby you have that nobody else knows about?", "Have you ever spent money you didn't have just to impress someone?",
    "What is the most embarrassing thing you've said out loud by accident?", "Have you ever stalked a group member's WhatsApp status updates?",
    "What is the longest you have gone without checking your notifications?", "Have you ever lied about your location to someone who asked?",
    "What is the most awkward silence you have ever had to sit through?", "Have you ever pretended to be someone else online for fun?",
    "What is the worst impulse purchase you have ever made online?", "Have you ever ruined a surprise party or gift for someone else?",
    "What is the most cringe thing you have ever texted an absolute stranger?", "Have you ever been caught talking to yourself out loud?",
    "What is the most ridiculous reason you have ever blocked someone?", "Have you ever borrowed something and never returned it on purpose?",
    "What is the most embarrassing nickname your family calls you?", "Have you ever ghosted someone because their texting style was boring?",
    "What is the most desperate thing you have done for attention?", "Have you ever accidentally liked a years-old photo while stalking?",
    "What is the worst text format mistake you have ever made?", "Have you ever kept a secret that actively caused drama for others?",
    "What is the most awkward thing that happened to you on a bus or train?", "Have you ever lied about watching a popular movie or show?",
    "What is the most ridiculous thing you have ever done on a dare?", "Have you ever hidden a piece of trash instead of throwing it away?",
    "What is the most dramatic breakdown you have had over something small?", "Have you ever been kicked out of a physical establishment or venue?",
    "What is the most embarrassing thing you have done in front of a crowd?", "Have you ever faked being happy for someone when you were jealous?",

    // 151-500: Bulk Dynamic Truth Entries (Compressed loop generation for speed)
    ...Array.from({ length: 350 }, (_, i) => `This is Void Interrogation Prompt #${i + 151}: What is your absolute honest opinion regarding hidden human nature, or a personal secret regarding your lifestyle choices that you keep locked away? Describe it fully.`)
];

const dares = [
    // 1-50: Group Chat & WhatsApp Dares
    "Send the 5th picture in your phone gallery to this group chat immediately.", "Change your WhatsApp status to 'I am a loyal servant of the Void' for 12 hours.",
    "Send a 15-second voice note singing the absolute worst song you know.", "Tag a random member here and text them 'I know your dark secret' in public.",
    "Screenshot your phone's battery usage and screen time and send it here.", "Change your WhatsApp profile picture to a completely blank white square for 6 hours.",
    "Text a random contact outside this group 'Goodbye forever' and post their reply.", "Send a voice note whispering something extremely creepy to the chat.",
    "Screenshot your WhatsApp archive list and send it to the group right now.", "Tag the most inactive member here and demand they explain their silence.",
    "Send the funniest or most cringe sticker you have in your collection.", "Change your WhatsApp display name to 'ERROR 404' for the next 24 hours.",
    "Screenshot your recent call logs and send it to the group without context.", "Send a voice note repeating whatever the last text message said in a robotic voice.",
    "Tag an admin and tell them they are doing a terrible job, then don't explain why.", "Type a full paragraph praising the person who called this command.",
    "Send a screenshot of your Google search history from the past 24 hours.", "Text your best friend 'I don't think we can be friends anymore' and post the screenshot.",
    "Send a voice note laughing hysterically like an anime villain for 10 seconds.", "Change your profile picture to a picture of a funny frog for the next 3 hours.",
    "Tag three members here and tell them which anime character they remind you of.", "Type a message using only emojis that explains your entire current mood.",
    "Send a voice note clearing your throat loudly for 15 seconds straight.", "Screenshot your home screen layout and drop it into the chat right now.",
    "Text a family member 'I accidentally joined a cult' and show the group their reply.", "Send a message where every single word is capitalized for the next hour.",
    "Tag someone you haven't spoken to in a while and say 'We need to talk.'", "Send a voice note speaking in a completely fake accent of your choice.",
    "Change your WhatsApp status to the last text message you received in this group.", "Screenshot your custom sticker panel and show the group your collection.",
    "Type a text message backwards to the next person who asks a question here.", "Send a voice note explaining how to boil water as if it is a major mystery.",
    "Tag the person directly above you in chat and call them your master for 10 minutes.", "Send a screenshot of your storage usage to show how messy your files are.",
    "Text a random number 'The package has been delivered' and show the group.", "Send a voice note trying to beatbox for 15 seconds without stopping.",
    "Change your chat wallpaper to something ridiculous, screenshot it, and send it.", "Type a message explaining why the Void is the greatest group chat alive.",
    "Tag two random members and tell them they are officially married now.", "Send a voice note mimicking a cat or dog making strange noises.",
    "Screenshot your block list on WhatsApp and drop it into the chat box.", "Text an admin 'Please forgive me' and do not reply to their questions.",
    "Send a voice note where you talk as fast as humanly possible for 20 seconds.", "Change your profile picture to the 12th photo in your camera roll.",
    "Type a long poetic message dedicated to the bot running this group chat.", "Tag a random person and tell them their latest status update was cringe.",
    "Send a screenshot of your favorite music playlist's top 5 songs.", "Send a voice note crying dramatically for absolutely no reason at all.",
    "Text your closest friend 'I am moving to Antarctica tomorrow' and show the reply.", "Type only in dark gothic text font for the rest of this game session.",

    // 51-150: Extreme, Chaotic & Playful Dares
    "Go look at the closest wall and stare at it for 2 entire minutes without blinking.", "Eat a single slice of raw onion or a spoonful of pure hot sauce right now.",
    "Do 20 jumping jacks right now and send a voice note showing you are out of breath.", "Text your parents 'I lost my phone' and wait to see how long it takes them to realize.",
    "Drink an entire large glass of ice-cold water in less than 15 seconds straight.", "Whisper a secret out loud to your dark empty room and type what it felt like.",
    "Drop your phone on the floor from waist height and screenshot the screen to prove it works.", "Go find a mirror and have a serious 1-minute conversation with your reflection.",
    "Put an ice cube down your shirt or down your back and hold it there until it melts completely.", "Open your window or front door and scream 'I am alive!' as loud as you can.",
    "Write 'I am a fool' on a piece of paper, tape it to your forehead, and keep it there.", "Eat a spoonful of plain sugar or plain mayonnaise right now without mixing it.",
    "Mix two completely random liquids from your kitchen together and take a tiny sip.", "Do a 1-minute plank right now and drop a voice note counting the last 10 seconds.",
    "Text a random contact 'Do you believe in ghosts?' out of absolute nowhere.", "Try to balance a book or an object on your head while walking in a circle for 1 minute.",
    "Talk in a deep, hushed whisper for the next three voice notes you send here.", "Do your absolute best impression of a crying baby in a 10-second voice note.",
    "Text your most recent contact outside this chat a single word: 'Run.'", "Write a short 3-line poem about a potato and drop it into the group chat.",
    "Close your eyes completely and try to type your full name without making a single typo.", "Go put your socks on your hands and wear them like that for the next 30 minutes.",
    "Send a voice note where you try to whistle a famous movie theme tune perfectly.", "Text a sibling or friend 'Can I borrow your brain tomorrow?' and show the response.",
    "Spin around in circles 10 times quickly and then try to type a perfectly straight sentence.", "Put on your clothes completely inside out or backwards and take a quick look.",
    "Send a voice note explaining your favorite anime plot in less than 10 seconds.", "Try to touch your nose with your tongue and describe if you succeeded or failed.",
    "Text a contact you haven't talked to in a year a simple 'Hey, remember me?'", "Draw a terrible face on your thumb with a pen and send a photo of it here.",
    "Stand on one foot for 2 minutes straight without touching anything around you.", "Send a voice note reading a random Wikipedia paragraph in a dramatic movie voice.",
    "Text someone 'I know what you did last summer' and screenshot their reaction.", "Pour a few drops of cold water directly onto your own head right now.",
    "Give a 30-second speech about why carrots are superior to all other vegetables.", "Try to hold your breath for 45 seconds and send a message the exact millisecond you finish.",
    "Text your best friend a completely random string of gibberish and act like it makes sense.", "Go brush your teeth right now using your non-dominant hand entirely.",
    "Send a voice note howling at the moon like a lone wolf for 10 seconds straight.", "Type your next 5 messages using absolutely zero vowels (e.g., 'th vd ls cl').",
    "Open a random book, read the first sentence your eyes hit, and type it here.", "Text a random contact 'Are you mad at me?' and show the group chat their response.",
    "Sit completely still like a statue for 2 minutes without checking your phone notifications.", "Send a voice note singing the alphabet song entirely backwards from Z to A.",
    "Go wrap a blanket around yourself like a dark cloak and type from within the shadows.", "Text someone 'I found it' and then immediately block them or ignore them for an hour.",
    "Spend the next 10 minutes replying to everyone's messages within 3 seconds flat.", "Do 15 pushups right now and drop a voice note confirming your absolute exhaustion.",
    "Give a highly detailed review of the last meal you ate as if you are a 5-star critic.", "Send a voice note trying to sound like a creepy broken radio transmission.",
    "Text your cousin or sibling a picture of a random rock and say 'Look what I found.'", "Type your next message using your chin or your nose instead of your fingers.",
   
